In [3]:
import pandas as pd
import numpy as np
import os
import sys

In [4]:
df = pd.read_csv('/Users/prasadpilankar/Documents/BAN/DE2025/Comtrade-Analytics/data-cleaning/cleandata_trade.csv')
df.head()

,refperiodid,freqcode,typecode,refyear,refmonth,reporteriso,reporterdesc,partneriso,partnerdesc,classificationcode,...,motcode,flowcode,cmdcode,cmddesc,qty,netwgt,cifvalue,fobvalue,primaryvalue,isreported
0,20080101,A,C,2008,52,GBR,United Kingdom,USA,USA,H3,...,0,X,TOTAL,All Commodities,0.0,0.0,0.000000e+00,6.516829e+10,6.516829e+10,True
1,20080101,A,C,2008,52,SAU,Saudi Arabia,GBR,United Kingdom,H3,...,0,X,TOTAL,All Commodities,0.0,0.0,0.000000e+00,3.446034e+08,3.446034e+08,True
2,20080101,A,C,2008,52,NLD,Netherlands,USA,USA,H3,...,0,M,TOTAL,All Commodities,0.0,0.0,3.995590e+10,0.000000e+00,3.995590e+10,True
3,20080101,A,C,2008,52,NLD,Netherlands,USA,USA,H3,...,0,X,TOTAL,All Commodities,0.0,0.0,0.000000e+00,2.429345e+10,2.429345e+10,True
4,20080101,A,C,2008,52,NGA,Nigeria,USA,USA,H2,...,0,M,TOTAL,All Commodities,0.0,0.0,2.313078e+09,0.000000e+00,2.313078e+09,True

In [5]:
df.columns

Index(['refperiodid', 'freqcode', 'typecode', 'refyear', 'refmonth',
       'reporteriso', 'reporterdesc', 'partneriso', 'partnerdesc',
       'classificationcode', 'aggrlevel', 'isleaf', 'moscode', 'motcode',
       'flowcode', 'cmdcode', 'cmddesc', 'qty', 'netwgt', 'cifvalue',
       'fobvalue', 'primaryvalue', 'isreported'],
      dtype='object')

In [6]:
selected_columns = [
    'typecode','refyear', 'reporteriso', 'reporterdesc',
    'partneriso', 'partnerdesc',
    'flowcode', 'cmdcode', 'cmddesc',
    'qty', 'netwgt', 'cifvalue', 'fobvalue','primaryvalue','isreported'
]

In [7]:
# Select only the relevant columns
df_selected = df[selected_columns]
df_selected.head()

,typecode,refyear,reporteriso,reporterdesc,partneriso,partnerdesc,flowcode,cmdcode,cmddesc,qty,netwgt,cifvalue,fobvalue,primaryvalue,isreported
0,C,2008,GBR,United Kingdom,USA,USA,X,TOTAL,All Commodities,0.0,0.0,0.000000e+00,6.516829e+10,6.516829e+10,True
1,C,2008,SAU,Saudi Arabia,GBR,United Kingdom,X,TOTAL,All Commodities,0.0,0.0,0.000000e+00,3.446034e+08,3.446034e+08,True
2,C,2008,NLD,Netherlands,USA,USA,M,TOTAL,All Commodities,0.0,0.0,3.995590e+10,0.000000e+00,3.995590e+10,True
3,C,2008,NLD,Netherlands,USA,USA,X,TOTAL,All Commodities,0.0,0.0,0.000000e+00,2.429345e+10,2.429345e+10,True
4,C,2008,NGA,Nigeria,USA,USA,M,TOTAL,All Commodities,0.0,0.0,2.313078e+09,0.000000e+00,2.313078e+09,True

In [8]:
df_selected['primaryvalue'] = pd.to_numeric(df_selected['primaryvalue'], errors='coerce').fillna(0).astype('int64')
df_selected['fobvalue'] = pd.to_numeric(df_selected['fobvalue'], errors='coerce').fillna(0).astype('int64')
df_selected['cifvalue'] = pd.to_numeric(df_selected['cifvalue'], errors='coerce').fillna(0).astype('int64')
df_selected.head()

<ipython-input-8-8f5149376abf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['primaryvalue'] = pd.to_numeric(df_selected['primaryvalue'], errors='coerce').fillna(0).astype('int64')
<ipython-input-8-8f5149376abf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['fobvalue'] = pd.to_numeric(df_selected['fobvalue'], errors='coerce').fillna(0).astype('int64')
<ipython-input-8-8f5149376abf>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['cifvalue'] = pd.to_numeric(df_selected['cifvalue'], errors='coerce').fillna(0).astype('int64')

,typecode,refyear,reporteriso,reporterdesc,partneriso,partnerdesc,flowcode,cmdcode,cmddesc,qty,netwgt,cifvalue,fobvalue,primaryvalue,isreported
0,C,2008,GBR,United Kingdom,USA,USA,X,TOTAL,All Commodities,0.0,0.0,0,65168291976,65168291976,True
1,C,2008,SAU,Saudi Arabia,GBR,United Kingdom,X,TOTAL,All Commodities,0.0,0.0,0,344603364,344603364,True
2,C,2008,NLD,Netherlands,USA,USA,M,TOTAL,All Commodities,0.0,0.0,39955896286,0,39955896286,True
3,C,2008,NLD,Netherlands,USA,USA,X,TOTAL,All Commodities,0.0,0.0,0,24293452648,24293452648,True
4,C,2008,NGA,Nigeria,USA,USA,M,TOTAL,All Commodities,0.0,0.0,2313078307,0,2313078307,True

In [9]:
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18320 entries, 0 to 18319
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   typecode      18320 non-null  object
 1   refyear       18320 non-null  int64
 2   reporteriso   18320 non-null  object
 3   reporterdesc  18320 non-null  object
 4   partneriso    18320 non-null  object
 5   partnerdesc   18320 non-null  object
 6   flowcode      18320 non-null  object
 7   cmdcode       18320 non-null  object
 8   cmddesc       18320 non-null  object
 9   qty           18320 non-null  float64
 10  netwgt        18320 non-null  float64
 11  cifvalue      18320 non-null  int64
 12  fobvalue      18320 non-null  int64
 13  primaryvalue  18320 non-null  int64
 14  isreported    18320 non-null  bool
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 2.0+ MB

In [10]:
cols_to_convert = ['reporteriso', 'reporterdesc', 'partneriso', 'partnerdesc', 'flowcode', 'cmdcode', 'cmddesc']
df_selected[cols_to_convert] = df_selected[cols_to_convert].astype('string')
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18320 entries, 0 to 18319
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   typecode      18320 non-null  object
 1   refyear       18320 non-null  int64
 2   reporteriso   18320 non-null  string
 3   reporterdesc  18320 non-null  string
 4   partneriso    18320 non-null  string
 5   partnerdesc   18320 non-null  string
 6   flowcode      18320 non-null  string
 7   cmdcode       18320 non-null  string
 8   cmddesc       18320 non-null  string
 9   qty           18320 non-null  float64
 10  netwgt        18320 non-null  float64
 11  cifvalue      18320 non-null  int64
 12  fobvalue      18320 non-null  int64
 13  primaryvalue  18320 non-null  int64
 14  isreported    18320 non-null  bool
dtypes: bool(1), float64(2), int64(4), object(1), string(7)
memory usage: 2.0+ MB

<ipython-input-10-ee5fe2c9da1f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected[cols_to_convert] = df_selected[cols_to_convert].astype('string')

In [11]:
df_selected.to_csv('/Users/prasadpilankar/Documents/BAN/DE2025/Comtrade-Analytics/data-transform/cleandata_trade_cleaned.csv', index=False)